Repository KDT3-MiniProject-8/MiniProject-FE, pull requests merged in 2023-02, with the labels that each got.

#11 Feature/design sign up
  package-lock.json
  package.json
  src/pages/Auth/SignUp.tsx
  src/style/globalStyles.tsx
  src/utils/list.ts
Labels: Refactor, Design

#13 Env: 배포 관련 redirects 설정, favicon 추가
  index.html
  public/_redirects
  public/favicon.png
Labels: Setting

#19 Design: 상품 상세페이지 상단 UI
  .prettierrc
  src/api/request.tsx
  src/pages/Auth/SignIn.tsx
  src/pages/Auth/SignUp.tsx
  src/pages/Detail.tsx
  src/style/globalStyles.tsx
Labels: Design

#21 Feat: 마이페이지 / 전체상품 페이지 / 관심상품 페이지 UI
  src/App.tsx
  src/components/allProducts/MyProducts.tsx
  src/components/allProducts/ProductsMenu.tsx
  src/components/common/cart/CartPageCard.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Navigation.tsx
  src/components/common/user/CartCard.tsx
  src/components/common/user/CartList.tsx
  src/components/common/user/Setting.tsx
  src/components/common/user/UserProfile.tsx
  src/pages/AllProducts.tsx
  src/pages/Cart.tsx
  src/pages/MyPage.tsx
  src/router.tsx
Labels: Feature, Design

#22 Feature/feat main
  .gitignore
  package-lock.json
  package.json
  src/api/api.tsx
  src/api/axios.tsx
  src/api/data.ts
  src/components/product/ProductItem.tsx
  src/pages/Auth/SignIn.tsx
  src/pages/Home.tsx
  src/style/globalStyles.tsx
Labels: Feature, Design

#25 Design: 상품 상세페이지 하단 UI
  src/api/api.tsx
  src/pages/Auth/SignUp.tsx
  src/pages/Detail.tsx
  src/style/globalStyles.tsx
Labels: Design

#27 Feat: 회원가입, 로그인 페이지 API 연결
  package-lock.json
  package.json
  src/api/api.tsx
  src/api/axios.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/SignUp.tsx
  src/router.tsx
Labels: Feature, API

#28 Feat: 회원가입 시 아이디중복검사 기능 추가
  index.html
  package-lock.json
  package.json
  src/api/api.tsx
  src/pages/Auth/SignUp.tsx
  src/utils/cookie.ts
Labels: Feature, API

#29 Feat: 로그인/로그아웃/비밀번호찾기 API연결 및 쿠키설정
  index.html
  package-lock.json
  package.json
  public/icon1.png
  public/icon2.png
  public/icon3.png
  public/icon4.png
  public/icon5.png
  public/icon6.png
  src/api/api.tsx
  src/components/allProducts/MyProducts.tsx
  src/components/allProducts/ProductsMenu.tsx
  src/components/common/CategoryBar.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Navigation.tsx
  src/pages/AllProducts.tsx
  src/pages/Auth/FindPassword.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/SignUp.tsx
  src/utils/cookie.ts
Labels: Feature, API, Design

#35 Feat: 상세페이지 API연결, 조건별 렌더링
  README.md
  public/6333070.jpg
  src/App.tsx
  src/api/api.tsx
  src/pages/Detail.tsx
  src/pages/NotFound.tsx
  src/style/globalStyles.tsx
Labels: Feature, API, Design

#36 Feat: 전체상품 페이지 api연결 및 무한스크롤 구현
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/allProductsApi.tsx
  src/components/allProducts/ProductCard.tsx
  src/components/allProducts/ProductsMenu.tsx
  src/components/cart/CartPageCard.tsx
  src/components/common/layout/CategoryBar.tsx
  src/components/common/layout/Header.tsx
  src/components/user/CartCard.tsx
  src/components/user/CartList.tsx
  src/components/user/Setting.tsx
  src/components/user/UserProfile.tsx
  src/pages/AllProducts.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
  src/pages/MyPage.tsx
  src/pages/allProducts/AllProducts.tsx
  src/pages/allProducts/CharterLoan.tsx
  src/pages/allProducts/DepositList.tsx
  src/pages/allProducts/MortgageLoan.tsx
  src/pages/allProducts/SavingsList.tsx
  src/router.tsx
  src/style/globalStyles.tsx
  vite.config.ts
Labels: Feature, API

#37 Feat: 상세페이지 장바구니, 관심상품 기능 추가
  src/api/api.tsx
  src/components/common/layout/CategoryBar.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/utils/list.ts
Labels: Feature, API, Design

#39 Design: 로그아웃버튼 배치 수정
  src/components/common/layout/Navigation.tsx
  src/pages/Detail.tsx
Labels: Design

#40 Feat: 로그인 상태에 따른 메인페이지 구성
  src/api/api.tsx
  src/components/cart/CartPageCard.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Navigation.tsx
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/style/globalStyles.tsx
  src/utils/cookie.ts
Labels: Feature, API, BugFix, Design

#45 Feat: 비회원 진입 불가 페이지 로그인안내
  src/api/api.tsx
  src/components/common/AlertLoginState.tsx
  src/components/wish/DepositWishList.tsx
  src/pages/Auth/FindPassword.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/SignUp.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
  src/pages/MyPage.tsx
  src/pages/Recommend.tsx
Labels: Feature, Design

#46 Feat: 상품 별 조회 탭 추가
  src/components/product/DepositsItem.tsx
  src/components/product/SearchItem.tsx
  src/pages/Search.tsx
Labels: Feature

#50 Feat: 장바구니 배열 로컬스토리지 저장
  package-lock.json
  package.json
  src/api/api.tsx
  src/api/axios.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
Labels: Feature

#51 Feat: 상품 클릭 시 해당 상품 상세페이지 연결
  src/api/api.tsx
  src/components/allProducts/DepositProductCard.tsx
  src/components/allProducts/LoanProductCard.tsx
  src/components/home/Main.tsx
  src/components/product/ProductItem.tsx
  src/pages/Auth/FindPassword.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
  src/router.tsx
Labels: Feature, Design

#53 Feat: 리덕스 툴킷 적용 및 유저 정보 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.tsx
  src/components/common/layout/Header.tsx
  src/components/common/layout/Navigation.tsx
  src/hooks/useDispatchHooks.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/store/store.tsx
  src/store/userSlice.tsx
Labels: Feature, API, Design

#54 Feat: 장바구니 기능 및 UI 완성
  src/api/api.tsx
  src/components/cart/CartPageCard.tsx
  src/components/product/ProductItem.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
  src/utils/list.ts
Labels: Feature, API, Design

#60 Feat: 로그인 상태관리 파일 구성
  README.md
  public/denied.jpg
  public/login.jpg
  src/api/api.tsx
  src/components/common/AlertLoginState.tsx
  src/components/common/layout/Navigation.tsx
  src/pages/Auth/Login.tsx
  src/pages/Detail.tsx
  src/pages/Search.tsx
  src/store/loginSlice.tsx
  src/store/store.tsx
Labels: Feature

#65 Refactor: api 코드 리팩토링
  src/api/api.tsx
  src/components/common/layout/Navigation.tsx
  src/components/user/Setting.tsx
  src/pages/Auth/FindPassword.tsx
  src/pages/Auth/SignUp.tsx
  src/pages/Detail.tsx
  src/store/loginSlice.tsx
  src/store/store.tsx
Labels: Refactor

#72 Design: alert, confirm 디자인 변경
  index.d.ts
  src/components/cart/CartPageCard.tsx
  src/components/common/layout/Navigation.tsx
  src/components/user/Setting.tsx
  src/pages/Auth/FindPassword.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/SignUp.tsx
  src/pages/Detail.tsx
  src/style/globalStyles.tsx
  src/utils/AlertModal.tsx
Labels: Design

#73 Feat: 회원가입페이지 이용약관 동의 체크박스 추가
  src/components/singup/Policy.tsx
  src/pages/Auth/SignUp.tsx
  src/utils/AlertModal.tsx
Labels: Feature, Design

#74 feat: 헤더 검색바 추가
  src/components/common/layout/Header.tsx
Labels: Feature, Design

#75 Refactor: 에러코드별 상세페이지 alert 수정
  src/api/api.tsx
  src/components/allProducts/DepositProductCard.tsx
  src/components/allProducts/LoanProductCard.tsx
  src/components/cart/CartPageCard.tsx
  src/components/product/ProductItem.tsx
  src/components/product/SearchItem.tsx
  src/components/singup/Policy.tsx
  src/components/user/PurchaseCard.tsx
  src/components/wish/WishCard.tsx
  src/pages/Detail.tsx
  src/style/globalStyles.tsx
Labels: Refactor, Design

#77 Design: 전체상품 페이지 디자인 수정
  README.md
  public/bag.png
  public/deposit1.png
  public/deposit2.png
  public/icon1.png
  public/icon2.png
  public/icon3.png
  public/icon4.png
  public/icon5.png
  public/icon6.png
  public/loan1.png
  public/loan2.png
  public/writing.png
  src/App.tsx
  src/api/wishApi.tsx
  src/components/allProducts/MyProducts.tsx
  src/components/allProducts/ProductsMenu.tsx
  src/pages/Auth/SignUp.tsx
Labels: Design

#80 Feat: 정렬 기능 추가
  src/pages/Search.tsx
Labels: Feature

#83 Design: 카드 그림자 추가
  src/components/allProducts/DepositProductCard.tsx
  src/components/allProducts/LoanProductCard.tsx
  src/components/cart/CartPageCard.tsx
  src/components/product/ProductItem.tsx
  src/components/product/SearchItem.tsx
  src/components/user/PurchaseCard.tsx
  src/components/wish/WishCard.tsx
  src/pages/Home.tsx
  src/pages/Search.tsx
Labels: Design

#85 Design: 전체상품페이지 배경색상 수정
  src/components/allProducts/MyProducts.tsx
  src/components/user/PurchaseList.tsx
Labels: Design

#90 Feat: 가입상품 관련 API연결, UI변경
  src/App.tsx
  src/api/wishApi.tsx
  src/components/allProducts/MyProducts.tsx
  src/components/user/MyMenu.tsx
  src/components/user/PurchaseCard.tsx
  src/components/user/UserProfile.tsx
  src/components/wish/DepositWishList.tsx
  src/pages/Purchase.tsx
  src/pages/allProducts/CharterLoan.tsx
  src/pages/allProducts/DepositList.tsx
  src/pages/allProducts/MortgageLoan.tsx
  src/pages/user/MyPage.tsx
  src/router.tsx
Labels: Feature, API, Design

#91 Feat: 로그아웃 시 장바구니 초기화
  src/App.tsx
  src/api/api.tsx
  src/components/cart/CartPageCard.tsx
  src/components/common/layout/Navigation.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
  src/pages/Home.tsx
Labels: Feature, API, BugFix, Design

#94 Design: 장바구니 금리 태그 추가
  public/bank-bs.png
  public/bank-ct.png
  public/bank-dg.png
  public/bank-gj.png
  public/bank-hn.png
  public/bank-ibk.png
  public/bank-kb.png
  public/bank-nh.png
  public/bank-sc.png
  public/bank-sh.png
  public/bank-suh.png
  public/bank-wr.png
  src/api/api.tsx
  src/components/allProducts/MyProducts.tsx
  src/components/cart/CartPageCard.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
Labels: Feature, Design

#96 Feat: 신청상품 상태별 토글 추가
  src/components/user/PurchaseCard.tsx
  src/pages/Purchase.tsx
  src/pages/Wish.tsx
Labels: Feature, Design

#97 Design: 페이지 텍스트 및 디자인 수정
  README.md
  src/components/user/CertifyUser.tsx
  src/components/user/EditUser.tsx
  src/pages/Wish.tsx
  src/pages/allProducts/AllProducts.tsx
Labels: Design

#99 Design: 상품카드 로고 추가, css 변경
  README.md
  public/bank-sh.png
  public/bank-wr.png
  src/components/allProducts/LoanProductCard.tsx
  src/components/cart/CartPageCard.tsx
  src/components/common/ProductCard.tsx
  src/components/product/ProductItem.tsx
  src/components/product/SearchItem.tsx
  src/components/user/PurchaseCard.tsx
  src/components/wish/WishCard.tsx
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/pages/Recommend.tsx
  src/pages/allProducts/CharterLoan.tsx
  src/pages/allProducts/DepositList.tsx
  src/pages/allProducts/MortgageLoan.tsx
  src/pages/allProducts/SavingsList.tsx
  src/style/globalStyles.tsx
Labels: Design

#100 Design: 상품카드 로고 추가, 신청상품 카드 시간 추가
  src/components/common/CartPageCard.tsx
  src/components/common/ProductCard.tsx
  src/components/product/SearchItem.tsx
  src/components/user/PurchaseCard.tsx
  src/components/wish/DepositWishList.tsx
  src/components/wish/WishCard.tsx
  src/pages/Cart.tsx
  src/pages/Purchase.tsx
  src/pages/Search.tsx
Labels: Refactor, Design

#101 Refactor: 리팩토링
  src/api/wishApi.tsx
  src/components/allProducts/AllProductList.tsx
  src/components/user/CertifyUser.tsx
  src/components/user/PurchaseCard.tsx
  src/components/user/UserInfo.tsx
  src/pages/AllProducts.tsx
  src/pages/FindPassword.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Purchase.tsx
  src/pages/SignUp.tsx
  src/pages/allProducts/CharterLoan.tsx
  src/pages/allProducts/DepositList.tsx
  src/pages/allProducts/MortgageLoan.tsx
  src/pages/allProducts/SavingsList.tsx
  src/pages/user/UserInfo.tsx
  src/router.tsx
  src/store/loginSlice.tsx
Labels: Feature, API, Refactor, Design

#102 Design: 가입/취소상품 없을 경우 안내 이미지 추가
  src/pages/Purchase.tsx
Labels: Design

#104 Feat: 관심상품, 가입상품 로그인 안내 추가
  src/pages/Purchase.tsx
  src/pages/Wish.tsx
Labels: Feature

#105 Design: 상세페이지 텍스트 줄바꿈 방식 변경
  src/pages/Detail.tsx
  src/pages/Home.tsx
Labels: Design

#107 Refactor: 인증 토큰 확인 위치 변경
  src/components/common/AlertLoginState.tsx
  src/pages/Cart.tsx
  src/pages/Detail.tsx
  src/pages/FindPassword.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Purchase.tsx
  src/pages/Recommend.tsx
  src/pages/Search.tsx
  src/pages/SignUp.tsx
  src/pages/Wish.tsx
  src/router.tsx
Labels: Refactor
